server:
  port: 8000


spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/tweetdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jps:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect